package:
  name: q2-composition
  version: { { PLUGIN_VERSION } }
source:
  path: ..
build:
  script: make install
requirements:
  host:
    - python {{ python }}
    - setuptools
    - versioningit
    - wheel
  run:
    - python {{ python }}
    - scikit-bio {{ scikit_bio }}
    - biom-format {{ biom_format }}
    - scipy {{ scipy }}
    - pandas {{ pandas }}
    - formulaic
    - bioconductor-phyloseq
    - bioconductor-ancombc
    - r-tidyverse
    - r-optparse
    - r-frictionless
    - qiime2 {{ qiime2_epoch }}.*
    - q2templates {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - altair
    - rpy2 {{ rpy2 }}
  build:
    - setuptools
    - versioningit
test:
  requires:
    - qiime2 >={{ qiime2 }}
    - q2templates >={{ q2templates }}
    - q2-types >={{ q2_types }}
    - pytest
  imports:
    - q2_composition
    - qiime2.plugins.composition
  commands:
    - py.test --pyargs q2_composition
about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
